In [46]:
import numpy as np
import pandas as pd

**Loading the data**

In [47]:
df = pd.read_csv(r'IPL-Auction-Dataset.zip')
df

,Unnamed: 0,Player's List,Base Price,TYPE,COST IN ₹ (CR.),Cost IN $ (000),2022 Squad,Team
0,0,Shivam Mavi,4000000,BOWLER,6.0,720.0,KKR,Gujarat Titans
1,1,Joshua Little,5000000,BOWLER,4.4,528.0,NaN,Gujarat Titans
2,2,Kane Williamson,20000000,BATSMAN,2.0,240.0,SRH,Gujarat Titans
3,3,K.S. Bharat,2000000,WICKETKEEPER,1.2,144.0,DC,Gujarat Titans
4,4,Mohit Sharma,5000000,BOWLER,0.5,60.0,NaN,Gujarat Titans
...,...,...,...,...,...,...,...,...
563,563,Dhruv Patel,2000000,ALL-ROUNDER,NaN,NaN,NaN,Unsold
564,564,Jack Prestwidge,2000000,ALL-ROUNDER,NaN,NaN,NaN,Unsold
565,565,Aditya Sarvate,2000000,ALL-ROUNDER,NaN,NaN,NaN,Unsold
566,566,Sagar Solanki,2000000,ALL-ROUNDER,NaN,NaN,NaN,Unsold
567,567,Prenelan Subrayen,2000000,ALL-ROUNDER,NaN,NaN,NaN,Unsold

In [48]:
df.head()

,Unnamed: 0,Player's List,Base Price,TYPE,COST IN ₹ (CR.),Cost IN $ (000),2022 Squad,Team
0,0,Shivam Mavi,4000000,BOWLER,6.0,720.0,KKR,Gujarat Titans
1,1,Joshua Little,5000000,BOWLER,4.4,528.0,NaN,Gujarat Titans
2,2,Kane Williamson,20000000,BATSMAN,2.0,240.0,SRH,Gujarat Titans
3,3,K.S. Bharat,2000000,WICKETKEEPER,1.2,144.0,DC,Gujarat Titans
4,4,Mohit Sharma,5000000,BOWLER,0.5,60.0,NaN,Gujarat Titans

In [49]:
df.loc[1]

Unnamed: 0                      1
Player's List       Joshua Little
Base Price                5000000
TYPE                       BOWLER
COST IN ₹ (CR.)               4.4
Cost IN $ (000)             528.0
2022 Squad                    NaN
Team               Gujarat Titans
Name: 1, dtype: object

In [50]:
df.shape

(568, 8)

In [51]:
df.drop(['Unnamed: 0'], axis=1, inplace=True)

In [52]:
df

,Player's List,Base Price,TYPE,COST IN ₹ (CR.),Cost IN $ (000),2022 Squad,Team
0,Shivam Mavi,4000000,BOWLER,6.0,720.0,KKR,Gujarat Titans
1,Joshua Little,5000000,BOWLER,4.4,528.0,NaN,Gujarat Titans
2,Kane Williamson,20000000,BATSMAN,2.0,240.0,SRH,Gujarat Titans
3,K.S. Bharat,2000000,WICKETKEEPER,1.2,144.0,DC,Gujarat Titans
4,Mohit Sharma,5000000,BOWLER,0.5,60.0,NaN,Gujarat Titans
...,...,...,...,...,...,...,...
563,Dhruv Patel,2000000,ALL-ROUNDER,NaN,NaN,NaN,Unsold
564,Jack Prestwidge,2000000,ALL-ROUNDER,NaN,NaN,NaN,Unsold
565,Aditya Sarvate,2000000,ALL-ROUNDER,NaN,NaN,NaN,Unsold
566,Sagar Solanki,2000000,ALL-ROUNDER,NaN,NaN,NaN,Unsold
567,Prenelan Subrayen,2000000,ALL-ROUNDER,NaN,NaN,NaN,Unsold

In [53]:
df.head()

,Player's List,Base Price,TYPE,COST IN ₹ (CR.),Cost IN $ (000),2022 Squad,Team
0,Shivam Mavi,4000000,BOWLER,6.0,720.0,KKR,Gujarat Titans
1,Joshua Little,5000000,BOWLER,4.4,528.0,NaN,Gujarat Titans
2,Kane Williamson,20000000,BATSMAN,2.0,240.0,SRH,Gujarat Titans
3,K.S. Bharat,2000000,WICKETKEEPER,1.2,144.0,DC,Gujarat Titans
4,Mohit Sharma,5000000,BOWLER,0.5,60.0,NaN,Gujarat Titans

In [54]:
df.tail()

,Player's List,Base Price,TYPE,COST IN ₹ (CR.),Cost IN $ (000),2022 Squad,Team
563,Dhruv Patel,2000000,ALL-ROUNDER,NaN,NaN,NaN,Unsold
564,Jack Prestwidge,2000000,ALL-ROUNDER,NaN,NaN,NaN,Unsold
565,Aditya Sarvate,2000000,ALL-ROUNDER,NaN,NaN,NaN,Unsold
566,Sagar Solanki,2000000,ALL-ROUNDER,NaN,NaN,NaN,Unsold
567,Prenelan Subrayen,2000000,ALL-ROUNDER,NaN,NaN,NaN,Unsold

In [55]:
df.sample()

,Player's List,Base Price,TYPE,COST IN ₹ (CR.),Cost IN $ (000),2022 Squad,Team
64,Rovman Powell,Retained,BATSMAN,0.0,0.0,DC,Delhi Capitals

In [56]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 568 entries, 0 to 567
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Player's List    568 non-null    object
 1   Base Price       568 non-null    object
 2   TYPE             568 non-null    object
 3   COST IN ₹ (CR.)  243 non-null    float64
 4   Cost IN $ (000)  243 non-null    float64
 5   2022 Squad       230 non-null    object
 6   Team             568 non-null    object
dtypes: float64(2), object(5)
memory usage: 31.2+ KB

In [57]:
df.describe()

       COST IN ₹ (CR.)  Cost IN $ (000)
count       243.000000       243.000000
mean          0.687243        82.469136
std           2.511700       301.404032
min           0.000000         0.000000
25%           0.000000         0.000000
50%           0.000000         0.000000
75%           0.200000        24.000000
max          18.500000      2220.000000

In [61]:
df[["Player's List", "TYPE"]]

         Player's List          TYPE
0          Shivam Mavi        BOWLER
1        Joshua Little        BOWLER
2      Kane Williamson       BATSMAN
3          K.S. Bharat  WICKETKEEPER
4         Mohit Sharma        BOWLER
..                 ...           ...
563        Dhruv Patel   ALL-ROUNDER
564    Jack Prestwidge   ALL-ROUNDER
565     Aditya Sarvate   ALL-ROUNDER
566      Sagar Solanki   ALL-ROUNDER
567  Prenelan Subrayen   ALL-ROUNDER

[568 rows x 2 columns]

In [66]:
df.iloc[[0,2],[3,6]]

   COST IN ₹ (CR.)            Team
0              6.0  Gujarat Titans
2              2.0  Gujarat Titans

In [67]:
df.loc[[1,4]]

,Player's List,Base Price,TYPE,COST IN ₹ (CR.),Cost IN $ (000),2022 Squad,Team
1,Joshua Little,5000000,BOWLER,4.4,528.0,NaN,Gujarat Titans
4,Mohit Sharma,5000000,BOWLER,0.5,60.0,NaN,Gujarat Titans

In [68]:
df.isnull()

,Player's List,Base Price,TYPE,COST IN ₹ (CR.),Cost IN $ (000),2022 Squad,Team
0,False,False,False,False,False,False,False
1,False,False,False,False,False,True,False
2,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False
4,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...
563,False,False,False,True,True,True,False
564,False,False,False,True,True,True,False
565,False,False,False,True,True,True,False
566,False,False,False,True,True,True,False
567,False,False,False,True,True,True,False

In [69]:
df.isnull().sum()

Player's List        0
Base Price           0
TYPE                 0
COST IN ₹ (CR.)    325
Cost IN $ (000)    325
2022 Squad         338
Team                 0
dtype: int64

In [70]:
df.dropna()

,Player's List,Base Price,TYPE,COST IN ₹ (CR.),Cost IN $ (000),2022 Squad,Team
0,Shivam Mavi,4000000,BOWLER,6.0,720.0,KKR,Gujarat Titans
2,Kane Williamson,20000000,BATSMAN,2.0,240.0,SRH,Gujarat Titans
3,K.S. Bharat,2000000,WICKETKEEPER,1.2,144.0,DC,Gujarat Titans
5,Odean Smith,5000000,ALL-ROUNDER,0.5,60.0,PBKS,Gujarat Titans
7,Rahul Tewatia,Retained,ALL-ROUNDER,0.0,0.0,GT,Gujarat Titans
...,...,...,...,...,...,...,...
238,Abdul Samad,Retained,BATSMAN,0.0,0.0,SRH,Sunrisers Hyderabad
239,Abhishek Sharma,Retained,ALL-ROUNDER,0.0,0.0,SRH,Sunrisers Hyderabad
240,Aiden Markram,Retained,BATSMAN,0.0,0.0,SRH,Sunrisers Hyderabad
241,Bhuvneshwar Kumar,Retained,BOWLER,0.0,0.0,SRH,Sunrisers Hyderabad
242,Glenn Phillips,Retained,WICKETKEEPER,0.0,0.0,SRH,Sunrisers Hyderabad

In [122]:
df.fillna("UNSOLD")

,Player,Base Price,TYPE,Sold Price(CR.),Sold Price($),2022 Squad,Team
0,Shivam Mavi,4000000,BOWLER,6.0,720.0,KKR,Gujarat Titans
1,Joshua Little,5000000,BOWLER,4.4,528.0,UNSOLD,Gujarat Titans
2,Kane Williamson,20000000,BATSMAN,2.0,240.0,SRH,Gujarat Titans
3,K.S. Bharat,2000000,WICKETKEEPER,1.2,144.0,DC,Gujarat Titans
4,Mohit Sharma,5000000,BOWLER,0.5,60.0,UNSOLD,Gujarat Titans
...,...,...,...,...,...,...,...
563,Dhruv Patel,2000000,ALL-ROUNDER,UNSOLD,UNSOLD,UNSOLD,Unsold
564,Jack Prestwidge,2000000,ALL-ROUNDER,UNSOLD,UNSOLD,UNSOLD,Unsold
565,Aditya Sarvate,2000000,ALL-ROUNDER,UNSOLD,UNSOLD,UNSOLD,Unsold
566,Sagar Solanki,2000000,ALL-ROUNDER,UNSOLD,UNSOLD,UNSOLD,Unsold
567,Prenelan Subrayen,2000000,ALL-ROUNDER,UNSOLD,UNSOLD,UNSOLD,Unsold

In [73]:
df['Team'].unique()

array(['Gujarat Titans', 'Chennai Super Kings', 'Delhi Capitals',
       'Kolkata Knight Riders', 'Punjab Super Kings',
       'Lucknow Super Giants', 'Mumbai Indians',
       'Royal Challengers Banglore', 'Rajasthan Royals',
       'Sunrisers Hyderabad', 'Unsold'], dtype=object)

In [75]:
df["TYPE"].unique()

array(['BOWLER', 'BATSMAN', 'WICKETKEEPER', 'ALL-ROUNDER'], dtype=object)

In [76]:
df["2022 Squad"].unique()

array(['KKR', nan, 'SRH', 'DC', 'PBKS', 'GT', 'CSK', 'LSG', 'MI', 'RCB',
       'RR'], dtype=object)

In [78]:
df["Team"].nunique()

11

In [80]:
df["Team"].value_counts()

Team
Unsold                        325
Gujarat Titans                 25
Chennai Super Kings            25
Delhi Capitals                 25
Lucknow Super Giants           25
Royal Challengers Banglore     25
Rajasthan Royals               25
Sunrisers Hyderabad            25
Mumbai Indians                 24
Kolkata Knight Riders          22
Punjab Super Kings             22
Name: count, dtype: int64

In [83]:
df["TYPE"].value_counts()

TYPE
ALL-ROUNDER     213
BOWLER          189
BATSMAN          91
WICKETKEEPER     75
Name: count, dtype: int64

In [86]:
df[df["Team"]=="Royal Challengers Banglore"]

,Player's List,Base Price,TYPE,COST IN ₹ (CR.),Cost IN $ (000),2022 Squad,Team
168,Will Jacks,1500000,BATSMAN,3.2,384.0,NaN,Royal Challengers Banglore
169,Reece Topley,7500000,BOWLER,1.9,228.0,NaN,Royal Challengers Banglore
170,Rajan Kumar,2000000,BOWLER,0.7,84.0,NaN,Royal Challengers Banglore
171,Avinash Singh,2000000,BOWLER,0.6,72.0,NaN,Royal Challengers Banglore
172,Manoj Bhandage,2000000,ALL-ROUNDER,0.2,24.0,NaN,Royal Challengers Banglore
173,Sonu Yadav,2000000,ALL-ROUNDER,0.2,24.0,NaN,Royal Challengers Banglore
174,Himanshu Sharma,2000000,BOWLER,0.2,24.0,NaN,Royal Challengers Banglore
175,Rajat Patidar,Retained,BATSMAN,0.0,0.0,RCB,Royal Challengers Banglore
176,Mahipal Lomror,Retained,BOWLER,0.0,0.0,RCB,Royal Challengers Banglore
177,Shahbaz Ahamad,Retained,ALL-ROUNDER,0.0,0.0,RCB,Royal Challengers Banglore
178,Mohammed Siraj,Retained,BOWLER,0.0,0.0,RCB,Royal Challengers Banglore
179,Wanindu Hasaranga,Retained,ALL-ROUNDER,0.0,0.0,RCB,Royal Challengers Banglore
180,Karn Sharma,Retained,BOWLER,0.0,0.0,RCB,Royal Challengers Banglore
181,Virat Kohli,Retained,BATSMAN,0.0,0.0,RCB,Royal Challengers Banglore
182,Suyash Prabhudessai,Retained,ALL-ROUNDER,0.0,0.0,RCB,Royal Challengers Banglore
183,Siddharth Kaul,Retained,BOWLER,0.0,0.0,RCB,Royal Challengers Banglore
184,Finn Allen,Retained,BATSMAN,0.0,0.0,RCB,Royal Challengers Banglore
185,David Willey,Retained,ALL-ROUNDER,0.0,0.0,RCB,Royal Challengers Banglore
186,Anuj Rawat,Retained,WICKETKEEPER,0.0,0.0,RCB,Royal Challengers Banglore
187,Akash Deep,Retained,BOWLER,0.0,0.0,RCB,Royal Challengers Banglore
188,Dinesh Karthik,Retained,WICKETKEEPER,0.0,0.0,RCB,Royal Challengers Banglore
189,Faf Du Plessis,Retained,BATSMAN,0.0,0.0,RCB,Royal Challengers Banglore
190,Harshal Patel,Retained,ALL-ROUNDER,0.0,0.0,RCB,Royal Challengers Banglore
191,Glenn Maxwell,Retained,ALL-ROUNDER,0.0,0.0,RCB,Royal Challengers Banglore
192,Josh Hazlewood,Retained,BOWLER,0.0,0.0,RCB,Royal Challengers Banglore

In [87]:
df[df["TYPE"] == "BOWLER"]

,Player's List,Base Price,TYPE,COST IN ₹ (CR.),Cost IN $ (000),2022 Squad,Team
0,Shivam Mavi,4000000,BOWLER,6.0,720.0,KKR,Gujarat Titans
1,Joshua Little,5000000,BOWLER,4.4,528.0,NaN,Gujarat Titans
4,Mohit Sharma,5000000,BOWLER,0.5,60.0,NaN,Gujarat Titans
9,Rashid Khan,Retained,BOWLER,0.0,0.0,GT,Gujarat Titans
10,R. Sai Kishore,Retained,BOWLER,0.0,0.0,GT,Gujarat Titans
...,...,...,...,...,...,...,...
518,Trilok Nag,2000000,BOWLER,NaN,NaN,NaN,Unsold
519,Atal Bihari Rai,2000000,BOWLER,NaN,NaN,NaN,Unsold
520,Ramon Simmonds,2000000,BOWLER,NaN,NaN,NaN,Unsold
521,Rajeev Singh,2000000,BOWLER,NaN,NaN,NaN,Unsold
522,Mohd. Wasim,2000000,BOWLER,NaN,NaN,NaN,Unsold

In [92]:
df[(df["TYPE"] == "BOWLER") & (df["Team"] == "Unsold")]

,Player's List,Base Price,TYPE,COST IN ₹ (CR.),Cost IN $ (000),2022 Squad,Team
245,Chris Jordan,20000000,BOWLER,NaN,NaN,CSK,Unsold
246,Adam Milne,20000000,BOWLER,NaN,NaN,CSK,Unsold
247,Mujeeb Rahman,10000000,BOWLER,NaN,NaN,NaN,Unsold
248,Tabraiz Shamsi,10000000,BOWLER,NaN,NaN,NaN,Unsold
261,Lance Morris,3000000,BOWLER,NaN,NaN,NaN,Unsold
...,...,...,...,...,...,...,...
518,Trilok Nag,2000000,BOWLER,NaN,NaN,NaN,Unsold
519,Atal Bihari Rai,2000000,BOWLER,NaN,NaN,NaN,Unsold
520,Ramon Simmonds,2000000,BOWLER,NaN,NaN,NaN,Unsold
521,Rajeev Singh,2000000,BOWLER,NaN,NaN,NaN,Unsold
522,Mohd. Wasim,2000000,BOWLER,NaN,NaN,NaN,Unsold

In [96]:
df[(df["TYPE"] == "ALL-ROUNDER") & (df["Team"] == "Gujarat Titans")]

,Player's List,Base Price,TYPE,COST IN ₹ (CR.),Cost IN $ (000),2022 Squad,Team
5,Odean Smith,5000000,ALL-ROUNDER,0.5,60.0,PBKS,Gujarat Titans
7,Rahul Tewatia,Retained,ALL-ROUNDER,0.0,0.0,GT,Gujarat Titans
8,Pradeep Sangwan,Retained,ALL-ROUNDER,0.0,0.0,GT,Gujarat Titans
14,Vijay Shankar,Retained,ALL-ROUNDER,0.0,0.0,GT,Gujarat Titans
16,Hardik Pandya,Retained,ALL-ROUNDER,0.0,0.0,GT,Gujarat Titans
17,B. Sai Sudharsan,Retained,ALL-ROUNDER,0.0,0.0,GT,Gujarat Titans
20,Darshan Nalkande,Retained,ALL-ROUNDER,0.0,0.0,GT,Gujarat Titans
23,Jayant Yadav,Retained,ALL-ROUNDER,0.0,0.0,GT,Gujarat Titans

In [110]:
df[(df["COST IN ₹ (CR.)"] > 5) & (df["2022 Squad"] == "PBKS")]

,Player's List,Base Price,TYPE,COST IN ₹ (CR.),Cost IN $ (000),2022 Squad,Team
219,Mayank Agarwal,10000000,BATSMAN,8.25,990.0,PBKS,Sunrisers Hyderabad

In [114]:
df = df.rename(columns={"Player's List": "Player"})
df

,Player,Base Price,TYPE,COST IN ₹ (CR.),Cost IN $ (000),2022 Squad,Team
0,Shivam Mavi,4000000,BOWLER,6.0,720.0,KKR,Gujarat Titans
1,Joshua Little,5000000,BOWLER,4.4,528.0,NaN,Gujarat Titans
2,Kane Williamson,20000000,BATSMAN,2.0,240.0,SRH,Gujarat Titans
3,K.S. Bharat,2000000,WICKETKEEPER,1.2,144.0,DC,Gujarat Titans
4,Mohit Sharma,5000000,BOWLER,0.5,60.0,NaN,Gujarat Titans
...,...,...,...,...,...,...,...
563,Dhruv Patel,2000000,ALL-ROUNDER,NaN,NaN,NaN,Unsold
564,Jack Prestwidge,2000000,ALL-ROUNDER,NaN,NaN,NaN,Unsold
565,Aditya Sarvate,2000000,ALL-ROUNDER,NaN,NaN,NaN,Unsold
566,Sagar Solanki,2000000,ALL-ROUNDER,NaN,NaN,NaN,Unsold
567,Prenelan Subrayen,2000000,ALL-ROUNDER,NaN,NaN,NaN,Unsold

In [119]:
df.rename(columns = {
    "COST IN ₹ (CR.)": "Sold Price(CR.)",
    "Cost IN $ (000)": "Sold Price($)"
}, inplace=True)

In [120]:
df

,Player,Base Price,TYPE,Sold Price(CR.),Sold Price($),2022 Squad,Team
0,Shivam Mavi,4000000,BOWLER,6.0,720.0,KKR,Gujarat Titans
1,Joshua Little,5000000,BOWLER,4.4,528.0,NaN,Gujarat Titans
2,Kane Williamson,20000000,BATSMAN,2.0,240.0,SRH,Gujarat Titans
3,K.S. Bharat,2000000,WICKETKEEPER,1.2,144.0,DC,Gujarat Titans
4,Mohit Sharma,5000000,BOWLER,0.5,60.0,NaN,Gujarat Titans
...,...,...,...,...,...,...,...
563,Dhruv Patel,2000000,ALL-ROUNDER,NaN,NaN,NaN,Unsold
564,Jack Prestwidge,2000000,ALL-ROUNDER,NaN,NaN,NaN,Unsold
565,Aditya Sarvate,2000000,ALL-ROUNDER,NaN,NaN,NaN,Unsold
566,Sagar Solanki,2000000,ALL-ROUNDER,NaN,NaN,NaN,Unsold
567,Prenelan Subrayen,2000000,ALL-ROUNDER,NaN,NaN,NaN,Unsold

In [123]:
df.columns = df.columns.str.upper()

In [124]:
df

,PLAYER,BASE PRICE,TYPE,SOLD PRICE(CR.),SOLD PRICE($),2022 SQUAD,TEAM
0,Shivam Mavi,4000000,BOWLER,6.0,720.0,KKR,Gujarat Titans
1,Joshua Little,5000000,BOWLER,4.4,528.0,UNSOLD,Gujarat Titans
2,Kane Williamson,20000000,BATSMAN,2.0,240.0,SRH,Gujarat Titans
3,K.S. Bharat,2000000,WICKETKEEPER,1.2,144.0,DC,Gujarat Titans
4,Mohit Sharma,5000000,BOWLER,0.5,60.0,UNSOLD,Gujarat Titans
...,...,...,...,...,...,...,...
563,Dhruv Patel,2000000,ALL-ROUNDER,UNSOLD,UNSOLD,UNSOLD,Unsold
564,Jack Prestwidge,2000000,ALL-ROUNDER,UNSOLD,UNSOLD,UNSOLD,Unsold
565,Aditya Sarvate,2000000,ALL-ROUNDER,UNSOLD,UNSOLD,UNSOLD,Unsold
566,Sagar Solanki,2000000,ALL-ROUNDER,UNSOLD,UNSOLD,UNSOLD,Unsold
567,Prenelan Subrayen,2000000,ALL-ROUNDER,UNSOLD,UNSOLD,UNSOLD,Unsold

In [125]:
df["PLAYER"].str.len()

0      11
1      13
2      15
3      11
4      12
       ..
563    11
564    15
565    14
566    13
567    17
Name: PLAYER, Length: 568, dtype: int64

In [131]:
df[df["PLAYER"].str.contains("sharma", case=False)]

,PLAYER,BASE PRICE,TYPE,SOLD PRICE(CR.),SOLD PRICE($),2022 SQUAD,TEAM
4,Mohit Sharma,5000000,BOWLER,0.5,60.0,UNSOLD,Gujarat Titans
54,Ishant Sharma,5000000,BOWLER,0.5,60.0,UNSOLD,Delhi Capitals
82,Suyash Sharma,2000000,BOWLER,0.2,24.0,UNSOLD,Kolkata Knight Riders
107,Jitesh Sharma,Retained,WICKETKEEPER,0.0,0.0,PBKS,Punjab Super Kings
140,Karan Sharma,Retained,ALL-ROUNDER,0.0,0.0,LSG,Lucknow Super Giants
155,Rohit Sharma,Retained,BATSMAN,0.0,0.0,MI,Mumbai Indians
174,Himanshu Sharma,2000000,BOWLER,0.2,24.0,UNSOLD,Royal Challengers Banglore
180,Karn Sharma,Retained,BOWLER,0.0,0.0,RCB,Royal Challengers Banglore
221,Vivrant Sharma,2000000,ALL-ROUNDER,2.6,312.0,UNSOLD,Sunrisers Hyderabad
239,Abhishek Sharma,Retained,ALL-ROUNDER,0.0,0.0,SRH,Sunrisers Hyderabad
281,Sandeep Sharma,5000000,BOWLER,UNSOLD,UNSOLD,PBKS,Unsold
326,Shivam Sharma,2000000,BOWLER,UNSOLD,UNSOLD,UNSOLD,Unsold
381,Bharat Sharma,2000000,WICKETKEEPER,UNSOLD,UNSOLD,UNSOLD,Unsold
401,Aman Sharma,2000000,BOWLER,UNSOLD,UNSOLD,UNSOLD,Unsold
469,Ashok Sharma,2000000,BOWLER,UNSOLD,UNSOLD,UNSOLD,Unsold
496,Ravi Sharma,2000000,BOWLER,UNSOLD,UNSOLD,UNSOLD,Unsold
542,Shivam Sharma,2000000,ALL-ROUNDER,UNSOLD,UNSOLD,UNSOLD,Unsold
555,Shubham Sharma,2000000,ALL-ROUNDER,UNSOLD,UNSOLD,UNSOLD,Unsold

In [139]:
df["SOLD PRICE($)"] = pd.to_numeric(df["SOLD PRICE($)"], errors="coerce")
df["Expensive"] = df["SOLD PRICE($)"].apply(
    lambda x: "YES" if  pd.notna(x) and x >= 15 else "NO"
)

In [140]:
df

,PLAYER,BASE PRICE,TYPE,SOLD PRICE(CR.),SOLD PRICE($),2022 SQUAD,TEAM,Expensive
0,Shivam Mavi,4000000,BOWLER,6.0,720.0,KKR,Gujarat Titans,YES
1,Joshua Little,5000000,BOWLER,4.4,528.0,UNSOLD,Gujarat Titans,YES
2,Kane Williamson,20000000,BATSMAN,2.0,240.0,SRH,Gujarat Titans,YES
3,K.S. Bharat,2000000,WICKETKEEPER,1.2,144.0,DC,Gujarat Titans,YES
4,Mohit Sharma,5000000,BOWLER,0.5,60.0,UNSOLD,Gujarat Titans,YES
...,...,...,...,...,...,...,...,...
563,Dhruv Patel,2000000,ALL-ROUNDER,UNSOLD,NaN,UNSOLD,Unsold,NO
564,Jack Prestwidge,2000000,ALL-ROUNDER,UNSOLD,NaN,UNSOLD,Unsold,NO
565,Aditya Sarvate,2000000,ALL-ROUNDER,UNSOLD,NaN,UNSOLD,Unsold,NO
566,Sagar Solanki,2000000,ALL-ROUNDER,UNSOLD,NaN,UNSOLD,Unsold,NO
567,Prenelan Subrayen,2000000,ALL-ROUNDER,UNSOLD,NaN,UNSOLD,Unsold,NO

In [142]:
df["Expensive"].value_counts()

Expensive
NO     488
YES     80
Name: count, dtype: int64

In [145]:
df["SOLD PRICE(CR.)"] = pd.to_numeric(df["SOLD PRICE(CR.)"], errors="coerce")
df["Expe. IN $"] = df["SOLD PRICE(CR.)"].apply(
    lambda y: "YES" if pd.notna(y) and y >= 4 else "NO"
)

In [146]:
df

,PLAYER,BASE PRICE,TYPE,SOLD PRICE(CR.),SOLD PRICE($),2022 SQUAD,TEAM,Expensive,Expe. IN $
0,Shivam Mavi,4000000,BOWLER,6.0,720.0,KKR,Gujarat Titans,YES,YES
1,Joshua Little,5000000,BOWLER,4.4,528.0,UNSOLD,Gujarat Titans,YES,YES
2,Kane Williamson,20000000,BATSMAN,2.0,240.0,SRH,Gujarat Titans,YES,NO
3,K.S. Bharat,2000000,WICKETKEEPER,1.2,144.0,DC,Gujarat Titans,YES,NO
4,Mohit Sharma,5000000,BOWLER,0.5,60.0,UNSOLD,Gujarat Titans,YES,NO
...,...,...,...,...,...,...,...,...,...
563,Dhruv Patel,2000000,ALL-ROUNDER,NaN,NaN,UNSOLD,Unsold,NO,NO
564,Jack Prestwidge,2000000,ALL-ROUNDER,NaN,NaN,UNSOLD,Unsold,NO,NO
565,Aditya Sarvate,2000000,ALL-ROUNDER,NaN,NaN,UNSOLD,Unsold,NO,NO
566,Sagar Solanki,2000000,ALL-ROUNDER,NaN,NaN,UNSOLD,Unsold,NO,NO
567,Prenelan Subrayen,2000000,ALL-ROUNDER,NaN,NaN,UNSOLD,Unsold,NO,NO

In [150]:
df.drop(columns=["COUNTRY"], inplace=True)

In [151]:
df

,PLAYER,BASE PRICE,TYPE,SOLD PRICE(CR.),SOLD PRICE($),2022 SQUAD,TEAM,Expensive,Expe. IN $
0,Shivam Mavi,4000000,BOWLER,6.0,720.0,KKR,Gujarat Titans,YES,YES
1,Joshua Little,5000000,BOWLER,4.4,528.0,UNSOLD,Gujarat Titans,YES,YES
2,Kane Williamson,20000000,BATSMAN,2.0,240.0,SRH,Gujarat Titans,YES,NO
3,K.S. Bharat,2000000,WICKETKEEPER,1.2,144.0,DC,Gujarat Titans,YES,NO
4,Mohit Sharma,5000000,BOWLER,0.5,60.0,UNSOLD,Gujarat Titans,YES,NO
...,...,...,...,...,...,...,...,...,...
563,Dhruv Patel,2000000,ALL-ROUNDER,NaN,NaN,UNSOLD,Unsold,NO,NO
564,Jack Prestwidge,2000000,ALL-ROUNDER,NaN,NaN,UNSOLD,Unsold,NO,NO
565,Aditya Sarvate,2000000,ALL-ROUNDER,NaN,NaN,UNSOLD,Unsold,NO,NO
566,Sagar Solanki,2000000,ALL-ROUNDER,NaN,NaN,UNSOLD,Unsold,NO,NO
567,Prenelan Subrayen,2000000,ALL-ROUNDER,NaN,NaN,UNSOLD,Unsold,NO,NO

In [152]:
df.insert(1, "COUNTRY", "Unknown")

In [153]:
df

,PLAYER,COUNTRY,BASE PRICE,TYPE,SOLD PRICE(CR.),SOLD PRICE($),2022 SQUAD,TEAM,Expensive,Expe. IN $
0,Shivam Mavi,Unknown,4000000,BOWLER,6.0,720.0,KKR,Gujarat Titans,YES,YES
1,Joshua Little,Unknown,5000000,BOWLER,4.4,528.0,UNSOLD,Gujarat Titans,YES,YES
2,Kane Williamson,Unknown,20000000,BATSMAN,2.0,240.0,SRH,Gujarat Titans,YES,NO
3,K.S. Bharat,Unknown,2000000,WICKETKEEPER,1.2,144.0,DC,Gujarat Titans,YES,NO
4,Mohit Sharma,Unknown,5000000,BOWLER,0.5,60.0,UNSOLD,Gujarat Titans,YES,NO
...,...,...,...,...,...,...,...,...,...,...
563,Dhruv Patel,Unknown,2000000,ALL-ROUNDER,NaN,NaN,UNSOLD,Unsold,NO,NO
564,Jack Prestwidge,Unknown,2000000,ALL-ROUNDER,NaN,NaN,UNSOLD,Unsold,NO,NO
565,Aditya Sarvate,Unknown,2000000,ALL-ROUNDER,NaN,NaN,UNSOLD,Unsold,NO,NO
566,Sagar Solanki,Unknown,2000000,ALL-ROUNDER,NaN,NaN,UNSOLD,Unsold,NO,NO
567,Prenelan Subrayen,Unknown,2000000,ALL-ROUNDER,NaN,NaN,UNSOLD,Unsold,NO,NO

In [154]:
df.insert(0, "PLAYER_ID", range(1, len(df)+1))

In [155]:
df

,PLAYER_ID,PLAYER,COUNTRY,BASE PRICE,TYPE,SOLD PRICE(CR.),SOLD PRICE($),2022 SQUAD,TEAM,Expensive,Expe. IN $
0,1,Shivam Mavi,Unknown,4000000,BOWLER,6.0,720.0,KKR,Gujarat Titans,YES,YES
1,2,Joshua Little,Unknown,5000000,BOWLER,4.4,528.0,UNSOLD,Gujarat Titans,YES,YES
2,3,Kane Williamson,Unknown,20000000,BATSMAN,2.0,240.0,SRH,Gujarat Titans,YES,NO
3,4,K.S. Bharat,Unknown,2000000,WICKETKEEPER,1.2,144.0,DC,Gujarat Titans,YES,NO
4,5,Mohit Sharma,Unknown,5000000,BOWLER,0.5,60.0,UNSOLD,Gujarat Titans,YES,NO
...,...,...,...,...,...,...,...,...,...,...,...
563,564,Dhruv Patel,Unknown,2000000,ALL-ROUNDER,NaN,NaN,UNSOLD,Unsold,NO,NO
564,565,Jack Prestwidge,Unknown,2000000,ALL-ROUNDER,NaN,NaN,UNSOLD,Unsold,NO,NO
565,566,Aditya Sarvate,Unknown,2000000,ALL-ROUNDER,NaN,NaN,UNSOLD,Unsold,NO,NO
566,567,Sagar Solanki,Unknown,2000000,ALL-ROUNDER,NaN,NaN,UNSOLD,Unsold,NO,NO
567,568,Prenelan Subrayen,Unknown,2000000,ALL-ROUNDER,NaN,NaN,UNSOLD,Unsold,NO,NO

In [159]:
df.groupby("TEAM")["PLAYER"].count()

TEAM
Chennai Super Kings            25
Delhi Capitals                 25
Gujarat Titans                 25
Kolkata Knight Riders          22
Lucknow Super Giants           25
Mumbai Indians                 24
Punjab Super Kings             22
Rajasthan Royals               25
Royal Challengers Banglore     25
Sunrisers Hyderabad            25
Unsold                        325
Name: PLAYER, dtype: int64

In [161]:
df.groupby("TEAM")["SOLD PRICE(CR.)"].sum()

TEAM
Chennai Super Kings           18.95
Delhi Capitals                15.00
Gujarat Titans                14.80
Kolkata Knight Riders          5.40
Lucknow Super Giants          19.80
Mumbai Indians                20.50
Punjab Super Kings            20.00
Rajasthan Royals               9.85
Royal Challengers Banglore     7.00
Sunrisers Hyderabad           35.70
Unsold                         0.00
Name: SOLD PRICE(CR.), dtype: float64

In [162]:
df.groupby("TEAM")["SOLD PRICE(CR.)"].mean()

TEAM
Chennai Super Kings           0.758000
Delhi Capitals                0.600000
Gujarat Titans                0.592000
Kolkata Knight Riders         0.245455
Lucknow Super Giants          0.792000
Mumbai Indians                0.854167
Punjab Super Kings            0.909091
Rajasthan Royals              0.394000
Royal Challengers Banglore    0.280000
Sunrisers Hyderabad           1.428000
Unsold                             NaN
Name: SOLD PRICE(CR.), dtype: float64

In [163]:
df.groupby("TEAM")["SOLD PRICE(CR.)"].agg(
    ["count", "sum", "mean", "max", "min"]
)

                            count    sum      mean    max  min
TEAM
Chennai Super Kings            25  18.95  0.758000  16.25  0.0
Delhi Capitals                 25  15.00  0.600000   5.50  0.0
Gujarat Titans                 25  14.80  0.592000   6.00  0.0
Kolkata Knight Riders          22   5.40  0.245455   1.50  0.0
Lucknow Super Giants           25  19.80  0.792000  16.00  0.0
Mumbai Indians                 24  20.50  0.854167  17.50  0.0
Punjab Super Kings             22  20.00  0.909091  18.50  0.0
Rajasthan Royals               25   9.85  0.394000   5.75  0.0
Royal Challengers Banglore     25   7.00  0.280000   3.20  0.0
Sunrisers Hyderabad            25  35.70  1.428000  13.25  0.0
Unsold                          0   0.00       NaN    NaN  NaN

In [165]:
df.groupby(["TEAM", "TYPE"])["PLAYER"].count()

TEAM                        TYPE
Chennai Super Kings         ALL-ROUNDER      10
                            BATSMAN           6
                            BOWLER            8
                            WICKETKEEPER      1
Delhi Capitals              ALL-ROUNDER      10
                            BATSMAN           5
                            BOWLER            8
                            WICKETKEEPER      2
Gujarat Titans              ALL-ROUNDER       8
                            BATSMAN           4
                            BOWLER            9
                            WICKETKEEPER      4
Kolkata Knight Riders       ALL-ROUNDER       6
                            BATSMAN           3
                            BOWLER           10
                            WICKETKEEPER      3
Lucknow Super Giants        ALL-ROUNDER      12
                            BATSMAN           2
                            BOWLER            9
                            WICKETKEEPER      2
Mumbai Indians              ALL-ROUNDER      12
                            BATSMAN           3
                            BOWLER            6
                            WICKETKEEPER      3
Punjab Super Kings          ALL-ROUNDER       9
                            BATSMAN           3
                            BOWLER            6
                            WICKETKEEPER      4
Rajasthan Royals            ALL-ROUNDER       5
                            BATSMAN           4
                            BOWLER           11
                            WICKETKEEPER      5
Royal Challengers Banglore  ALL-ROUNDER       8
                            BATSMAN           5
                            BOWLER           10
                            WICKETKEEPER      2
Sunrisers Hyderabad         ALL-ROUNDER       7
                            BATSMAN           6
                            BOWLER            8
                            WICKETKEEPER      4
Unsold                      ALL-ROUNDER     126
                            BATSMAN          50
                            BOWLER          104
                            WICKETKEEPER     45
Name: PLAYER, dtype: int64

In [169]:
df.pivot_table(
    values="SOLD PRICE($)",
    index="TEAM",
    columns="TYPE",
    aggfunc="mean"
)

TYPE                        ALL-ROUNDER  BATSMAN      BOWLER  WICKETKEEPER
TEAM
Chennai Super Kings          207.000000     14.0   15.000000           0.0
Delhi Capitals                 0.000000    168.0   90.000000         120.0
Gujarat Titans                 7.500000     60.0  145.333333          42.0
Kolkata Knight Riders         50.000000     20.0   12.000000          56.0
Lucknow Super Giants          18.500000      0.0   26.000000         960.0
Mumbai Indians               181.000000      0.0   44.000000           8.0
Punjab Super Kings           256.000000     16.0    4.000000           6.0
Rajasthan Royals             147.600000     30.0   21.818182          16.8
Royal Challengers Banglore     6.000000     76.8   40.800000           0.0
Sunrisers Hyderabad           82.285714    434.0   52.500000         171.0

In [170]:
df.pivot_table(
    values="SOLD PRICE(CR.)",
    index="TEAM",
    aggfunc="sum"
)

                            SOLD PRICE(CR.)
TEAM
Chennai Super Kings                   18.95
Delhi Capitals                        15.00
Gujarat Titans                        14.80
Kolkata Knight Riders                  5.40
Lucknow Super Giants                  19.80
Mumbai Indians                        20.50
Punjab Super Kings                    20.00
Rajasthan Royals                       9.85
Royal Challengers Banglore             7.00
Sunrisers Hyderabad                   35.70
Unsold                                 0.00

In [172]:
df.pivot_table(
    values="SOLD PRICE($)",
    index="TEAM",
    aggfunc="sum"
)

                            SOLD PRICE($)
TEAM
Chennai Super Kings                2274.0
Delhi Capitals                     1800.0
Gujarat Titans                     1776.0
Kolkata Knight Riders               648.0
Lucknow Super Giants               2376.0
Mumbai Indians                     2460.0
Punjab Super Kings                 2400.0
Rajasthan Royals                   1182.0
Royal Challengers Banglore          840.0
Sunrisers Hyderabad                4284.0
Unsold                                0.0

In [173]:
df.pivot_table(
    values="SOLD PRICE(CR.)",
    index="TEAM",
    aggfunc="mean"
)

                            SOLD PRICE(CR.)
TEAM
Chennai Super Kings                0.758000
Delhi Capitals                     0.600000
Gujarat Titans                     0.592000
Kolkata Knight Riders              0.245455
Lucknow Super Giants               0.792000
Mumbai Indians                     0.854167
Punjab Super Kings                 0.909091
Rajasthan Royals                   0.394000
Royal Challengers Banglore         0.280000
Sunrisers Hyderabad                1.428000