In [1]:
import numpy as np
import pandas as pd

Creating DataFrame

In [5]:
data = {
    'Name': ['Krunalsinh', 'Karmrajsinh', 'Raj', 'Ram'],
    'Age': ['21', '22', '24', '34'],
    'City': ["Surendranagar", 'Rajkot', 'Morbi', 'Surat'],
    'Salary': [60000, 20000, 40000, 54000]
}

df = pd.DataFrame(data)
df

          Name Age           City  Salary
0   Krunalsinh  21  Surendranagar   60000
1  Karmrajsinh  22         Rajkot   20000
2          Raj  24          Morbi   40000
3          Ram  34          Surat   54000

In [7]:
data_list = [
    ['Krunalsinh', 21, 'Surendranagar', 60000],
    ['Karmrajsinh', 22, 'Rajkot', 20000],
    ['Raj', 24, 'Morbi', 40000],
    ['Ram', 34 , 'Surat', 54000]
]
df_list = pd.DataFrame(data_list)
df_list

             0   1              2      3
0   Krunalsinh  21  Surendranagar  60000
1  Karmrajsinh  22         Rajkot  20000
2          Raj  24          Morbi  40000
3          Ram  34          Surat  54000

In [9]:
column = ["Name", "Age", "City", "Salary"]
df_list = pd.DataFrame(data_list, columns = column)
df_list

          Name  Age           City  Salary
0   Krunalsinh   21  Surendranagar   60000
1  Karmrajsinh   22         Rajkot   20000
2          Raj   24          Morbi   40000
3          Ram   34          Surat   54000

Selection and indexing of Columns

In [21]:
df_list

          Name  Age           City  Salary
0   Krunalsinh   21  Surendranagar   60000
1  Karmrajsinh   22         Rajkot   20000
2          Raj   24          Morbi   40000
3          Ram   34          Surat   54000

In [22]:
df_list['Name']

0     Krunalsinh
1    Karmrajsinh
2            Raj
3            Ram
Name: Name, dtype: object

In [23]:
df_list[['Name', 'City']]

          Name           City
0   Krunalsinh  Surendranagar
1  Karmrajsinh         Rajkot
2          Raj          Morbi
3          Ram          Surat

Creating a new column

In [24]:
df_list["Designation"] = ["Engineer", "Doctor", "Teacher", "Businessman"]

In [25]:
df_list

          Name  Age           City  Salary  Designation
0   Krunalsinh   21  Surendranagar   60000     Engineer
1  Karmrajsinh   22         Rajkot   20000       Doctor
2          Raj   24          Morbi   40000      Teacher
3          Ram   34          Surat   54000  Businessman

In [27]:
df_list.drop('Age', axis=1)

          Name           City  Salary  Designation
0   Krunalsinh  Surendranagar   60000     Engineer
1  Karmrajsinh         Rajkot   20000       Doctor
2          Raj          Morbi   40000      Teacher
3          Ram          Surat   54000  Businessman

In [28]:
df_list['Age'] = [20, 25, 22, 35]
df_list

          Name  Age           City  Salary  Designation
0   Krunalsinh   20  Surendranagar   60000     Engineer
1  Karmrajsinh   25         Rajkot   20000       Doctor
2          Raj   22          Morbi   40000      Teacher
3          Ram   35          Surat   54000  Businessman

Removing Columns

In [37]:
df_list.drop('Salary', axis=1)

          Name  Age  Designation
0   Krunalsinh   20     Engineer
1  Karmrajsinh   25       Doctor
2          Raj   22      Teacher
3          Ram   35  Businessman

In [38]:
df_list

          Name  Age  Salary  Designation
0   Krunalsinh   20   60000     Engineer
1  Karmrajsinh   25   20000       Doctor
2          Raj   22   40000      Teacher
3          Ram   35   54000  Businessman

In [42]:
df_list.drop("Age", axis=1)

          Name  Salary  Designation
0   Krunalsinh   60000     Engineer
1  Karmrajsinh   20000       Doctor
2          Raj   40000      Teacher
3          Ram   54000  Businessman

In [43]:
df_list

          Name  Age  Salary  Designation
0   Krunalsinh   20   60000     Engineer
1  Karmrajsinh   25   20000       Doctor
2          Raj   22   40000      Teacher
3          Ram   35   54000  Businessman

In [45]:
df_list.drop("Age", axis=1, inplace=True)

In [46]:
df_list

          Name  Salary  Designation
0   Krunalsinh   60000     Engineer
1  Karmrajsinh   20000       Doctor
2          Raj   40000      Teacher
3          Ram   54000  Businessman

Selecting Rows

In [47]:
df_list

          Name  Salary  Designation
0   Krunalsinh   60000     Engineer
1  Karmrajsinh   20000       Doctor
2          Raj   40000      Teacher
3          Ram   54000  Businessman

In [49]:
df_list.loc[0]

Name           Krunalsinh
Salary              60000
Designation      Engineer
Name: 0, dtype: object

In [50]:
df_list.loc[[0,1]]

          Name  Salary Designation
0   Krunalsinh   60000    Engineer
1  Karmrajsinh   20000      Doctor

Selecting Subsets of Rows and Columns

In [51]:
df_list

          Name  Salary  Designation
0   Krunalsinh   60000     Engineer
1  Karmrajsinh   20000       Doctor
2          Raj   40000      Teacher
3          Ram   54000  Businessman

In [52]:
df_list.loc[[0,1]][["Name","Salary"]]

          Name  Salary
0   Krunalsinh   60000
1  Karmrajsinh   20000

Conditional Selection

In [53]:
df_list

          Name  Salary  Designation
0   Krunalsinh   60000     Engineer
1  Karmrajsinh   20000       Doctor
2          Raj   40000      Teacher
3          Ram   54000  Businessman

In [54]:
df_list["Age"] = [21, 28, 18, 35]

In [55]:
df_list

          Name  Salary  Designation  Age
0   Krunalsinh   60000     Engineer   21
1  Karmrajsinh   20000       Doctor   28
2          Raj   40000      Teacher   18
3          Ram   54000  Businessman   35

In [57]:
# I only want to those people whose age above 25
df_list[df_list["Age"] > 25]

          Name  Salary  Designation  Age
1  Karmrajsinh   20000       Doctor   28
3          Ram   54000  Businessman   35

In [58]:
df_list[(df_list["Age"] > 25) & (df_list["Designation"] == "Doctor")]

          Name  Salary Designation  Age
1  Karmrajsinh   20000      Doctor   28