In [1]:
import numpy as np
import pandas as pd

Finding Missing Data

In [6]:
data = {
    'A':[1, 3, np.nan, 5, 6],
    'B':[np.nan, 5, 7,3,8],
    'C':[2, 6,8,np.nan, 2],
    'D':[7,9,np.nan, 4,np.nan]
}
df = pd.DataFrame(data)

In [7]:
df

     A    B    C    D
0  1.0  NaN  2.0  7.0
1  3.0  5.0  6.0  9.0
2  NaN  7.0  8.0  NaN
3  5.0  3.0  NaN  4.0
4  6.0  8.0  2.0  NaN

In [8]:
df.isna()

       A      B      C      D
0  False   True  False  False
1  False  False  False  False
2   True  False  False   True
3  False  False   True  False
4  False  False  False   True

In [9]:
df.isna().sum()

A    1
B    1
C    1
D    2
dtype: int64

In [10]:
df.isna().any()

A    True
B    True
C    True
D    True
dtype: bool

Removing Missing Data

In [11]:
df

     A    B    C    D
0  1.0  NaN  2.0  7.0
1  3.0  5.0  6.0  9.0
2  NaN  7.0  8.0  NaN
3  5.0  3.0  NaN  4.0
4  6.0  8.0  2.0  NaN

In [12]:
df.dropna()

     A    B    C    D
1  3.0  5.0  6.0  9.0

In [13]:
df

     A    B    C    D
0  1.0  NaN  2.0  7.0
1  3.0  5.0  6.0  9.0
2  NaN  7.0  8.0  NaN
3  5.0  3.0  NaN  4.0
4  6.0  8.0  2.0  NaN

In [19]:
df.dropna(thresh=3)

     A    B    C    D
0  1.0  NaN  2.0  7.0
1  3.0  5.0  6.0  9.0
3  5.0  3.0  NaN  4.0
4  6.0  8.0  2.0  NaN

Filling the Missing Data

In [20]:
df.fillna(0)

     A    B    C    D
0  1.0  0.0  2.0  7.0
1  3.0  5.0  6.0  9.0
2  0.0  7.0  8.0  0.0
3  5.0  3.0  0.0  4.0
4  6.0  8.0  2.0  0.0

In [21]:
df.fillna(1)

     A    B    C    D
0  1.0  1.0  2.0  7.0
1  3.0  5.0  6.0  9.0
2  1.0  7.0  8.0  1.0
3  5.0  3.0  1.0  4.0
4  6.0  8.0  2.0  1.0

In [22]:
values = {'A':1, 'B':10, 'C':20, 'D':30}
df.fillna(value=values)

     A     B     C     D
0  1.0  10.0   2.0   7.0
1  3.0   5.0   6.0   9.0
2  1.0   7.0   8.0  30.0
3  5.0   3.0  20.0   4.0
4  6.0   8.0   2.0  30.0

In [23]:
df

     A    B    C    D
0  1.0  NaN  2.0  7.0
1  3.0  5.0  6.0  9.0
2  NaN  7.0  8.0  NaN
3  5.0  3.0  NaN  4.0
4  6.0  8.0  2.0  NaN

In [24]:
df.fillna(df.mean())

      A     B    C         D
0  1.00  5.75  2.0  7.000000
1  3.00  5.00  6.0  9.000000
2  3.75  7.00  8.0  6.666667
3  5.00  3.00  4.5  4.000000
4  6.00  8.00  2.0  6.666667