In [2]:
import numpy as np
import pandas as pd

**Merging 2 Dataframes**

In [31]:
employees = pd.DataFrame({
    'Emp_id': [1,2,3,4,5],
    'Name': ['Krunalsinh', 'Raj', 'Ram', 'Shyam', 'Bharat'],
    'Department': ['HR', 'IT', 'CE', 'CIVIL', 'EC']
})

salaries = pd.DataFrame({
    'Emp_id': [1,2,3,6,7],
    'Salary': [60000, 30000, 45000, 50475, 23000],
    'Bonus': [5000, 2000, 12000, 1000, 2200]
})

In [32]:
employees

   Emp_id        Name Department
0       1  Krunalsinh         HR
1       2         Raj         IT
2       3         Ram         CE
3       4       Shyam      CIVIL
4       5      Bharat         EC

In [33]:
salaries

   Emp_id  Salary  Bonus
0       1   60000   5000
1       2   30000   2000
2       3   45000  12000
3       6   50475   1000
4       7   23000   2200

In [34]:
pd.merge(employees, salaries)

   Emp_id        Name Department  Salary  Bonus
0       1  Krunalsinh         HR   60000   5000
1       2         Raj         IT   30000   2000
2       3         Ram         CE   45000  12000

In [35]:
pd.merge(employees, salaries, on='Emp_id')

   Emp_id        Name Department  Salary  Bonus
0       1  Krunalsinh         HR   60000   5000
1       2         Raj         IT   30000   2000
2       3         Ram         CE   45000  12000

In [36]:
pd.merge(employees, salaries, on='Emp_id', how='outer')

   Emp_id        Name Department   Salary    Bonus
0       1  Krunalsinh         HR  60000.0   5000.0
1       2         Raj         IT  30000.0   2000.0
2       3         Ram         CE  45000.0  12000.0
3       4       Shyam      CIVIL      NaN      NaN
4       5      Bharat         EC      NaN      NaN
5       6         NaN        NaN  50475.0   1000.0
6       7         NaN        NaN  23000.0   2200.0

In [37]:
pd.merge(employees, salaries, on='Emp_id', how='left')

   Emp_id        Name Department   Salary    Bonus
0       1  Krunalsinh         HR  60000.0   5000.0
1       2         Raj         IT  30000.0   2000.0
2       3         Ram         CE  45000.0  12000.0
3       4       Shyam      CIVIL      NaN      NaN
4       5      Bharat         EC      NaN      NaN

In [38]:
pd.merge(employees, salaries, on='Emp_id', how='right')

   Emp_id        Name Department  Salary  Bonus
0       1  Krunalsinh         HR   60000   5000
1       2         Raj         IT   30000   2000
2       3         Ram         CE   45000  12000
3       6         NaN        NaN   50475   1000
4       7         NaN        NaN   23000   2200

**Concatination of 2 Dafaframes**

In [39]:
df1 = pd.DataFrame({
    'A':['A0','A1','A2'],
    'B':['B0','B1','B2'],
    'C':['C0','C1','C2']
})

df2 = pd.DataFrame({
    'A':['A3','A4','A5'],
    'B':['B3','B4','B5'],
    'C':['C3','C4','C5']
})

In [40]:
pd.concat([df1, df2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [41]:
pd.concat([df2, df1])

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [42]:
pd.concat([df1,df2], axis=1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

In [43]:
pd.concat([df2,df1], axis=1)

    A   B   C   A   B   C
0  A3  B3  C3  A0  B0  C0
1  A4  B4  C4  A1  B1  C1
2  A5  B5  C5  A2  B2  C2

**Joining of 2 Dafaframes**

In [45]:
df1 = pd.DataFrame({
    'Name':['Krunalsinh', 'Raj', 'Shyam']
}, index=[1,2,3])

df2 = pd.DataFrame({
    'Runs':[102, 42, 53]
}, index=[2,3,4])

In [46]:
df1

         Name
1  Krunalsinh
2         Raj
3       Shyam

In [47]:
df2

   Runs
2   102
3    42
4    53

In [48]:
df1.join(df2)

         Name   Runs
1  Krunalsinh    NaN
2         Raj  102.0
3       Shyam   42.0

In [50]:
df1.join(df2, how='outer')

         Name   Runs
1  Krunalsinh    NaN
2         Raj  102.0
3       Shyam   42.0
4         NaN   53.0

In [51]:
df2.join(df1)

   Runs   Name
2   102    Raj
3    42  Shyam
4    53    NaN

In [52]:
df2.join(df1, how='left')

   Runs   Name
2   102    Raj
3    42  Shyam
4    53    NaN

In [53]:
df2.join(df1, how='right')

    Runs        Name
1    NaN  Krunalsinh
2  102.0         Raj
3   42.0       Shyam