In [1]:
import numpy as np
import pandas as pd

**DataFrames Basic Operations**

In [4]:
df1 = pd.DataFrame({
    'A': [1,5,7,4,6],
    'B': [10, 54, 41, 63, 9],
    'C': [200, 355, 110, 276, 322]
})

In [5]:
df1

   A   B    C
0  1  10  200
1  5  54  355
2  7  41  110
3  4  63  276
4  6   9  322

In [6]:
df1.shape

(5, 3)

In [9]:
df1.columns

Index(['A', 'B', 'C'], dtype='object')

In [10]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [11]:
df1.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   4.600000  35.400000  252.600000
std    2.302173  24.905823   98.680292
min    1.000000   9.000000  110.000000
25%    4.000000  10.000000  200.000000
50%    5.000000  41.000000  276.000000
75%    6.000000  54.000000  322.000000
max    7.000000  63.000000  355.000000

In [12]:
df1['A'] + 12

0    13
1    17
2    19
3    16
4    18
Name: A, dtype: int64

**DataFrames Applying Functions**

In [14]:
df1

   A   B    C
0  1  10  200
1  5  54  355
2  7  41  110
3  4  63  276
4  6   9  322

In [15]:
def square(x):
    return x**2

In [18]:
df1['A'].apply(square)

0     1
1    25
2    49
3    16
4    36
Name: A, dtype: int64

In [19]:
df1.apply(square)

    A     B       C
0   1   100   40000
1  25  2916  126025
2  49  1681   12100
3  16  3969   76176
4  36    81  103684

In [23]:
df1['D'] = df1['A'].apply(square)
df1

   A   B    C   D
0  1  10  200   1
1  5  54  355  25
2  7  41  110  49
3  4  63  276  16
4  6   9  322  36

In [24]:
df1

   A   B    C   D
0  1  10  200   1
1  5  54  355  25
2  7  41  110  49
3  4  63  276  16
4  6   9  322  36

In [25]:
df1['C'] = df1['C'].apply(lambda X: X%2)

In [26]:
df1

   A   B  C   D
0  1  10  0   1
1  5  54  1  25
2  7  41  0  49
3  4  63  0  16
4  6   9  0  36